# Generated by Django 3.2.7 on 2021-09-08 20:41

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_5', '0002_auto_20210906_2210'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bouquet',
            managers=[
                ('shop', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='invoice',
            field=models.FileField(null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
